{
    'name': 'IT Helpdesk',
    'version': '19.0.1.1.0',
    'category': 'Services/Helpdesk',
    'summary': 'IT Support Ticketing System',
    'author': 'TechCarrot FZ-LLC',
    'depends': ['base', 'hr', 'mail', 'portal', 'web', 'board', 'employee_profile_change_request'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ticket_sequence.xml',
        'data/email_templates.xml',
        'data/ir_cron.xml',
        'data/automated_actions.xml',
        'data/ticket_categories_and_types.xml',
        'data/ticket_type.xml',
        'views/portal_ticket_detail.xml',
        'views/portal_it_ticket_approvals.xml',
        'views/portal_my_home_link.xml',
        'views/it_ticket_views.xml',
        'views/It_ticket_category_views.xml',
        'views/reporting_by_average_time.xml',
        'views/reporting_by_category.xml',
        'views/reporting_open_tickets.xml',
        'views/reporting_solved_tickets.xml',
        'views/ticket_workflow_config_view.xml',
        'views/it_dashboard.xml',
        'views/menu_items.xml',
        'wizards/reject_wizard_views.xml',
        'wizards/approve_wizard.xml',
        'wizards/it_reminder_config_wizard.xml',
        'wizards/duration_config_wizard.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
    'post_load': 'post_load',
    'post_migrate': 'post_migrate',
}